name: HBSN

pre_window: 
  - source /opt/ros/humble/setup.bash
  - source ../../ros2_ws//install/setup.bash

windows:
  - navstack:
      layout: tiled
      panes:
        - shell:
        #ROS2
        - bridge_unity:
          - ros2 run ros_tcp_endpoint default_server_endpoint
        - map_publisher:
          - ros2 run unity_sim map_publisher.py
        - global_path:
          - ros2 run base_nav global_planner.py
        - hbsn:
          - ros2 launch hbsn_ros hbsn_sim.launch.py
        - controller:
          - ros2 run base_nav dwa_controller_social.py --ros-args -p path_topic:=/local_path

        - agent_trajectories:
          - ros2 run agent_trajectory_prediction agent_trajectory_prediction_publisher.py 
        - visualization_trajs:
          - ros2 run agent_trajectory_prediction agent_trajectory_prediction_visualization.py

        - rviz:
          - ros2 launch unity_sim rviz.launch.py
        - trial:
          - cd ../..
          - ros2 run unity_sim trial_info_listener.py --ros-args -p method:=hbsn