# Learning params
learning:
  total_timesteps: 50000000
  n_steps: 512
  learning_rate: 0.00005
  num_envs: 10
  speed_time: 1.0
  save_model_frequency: 1000000
  curriculum:
    max_level: 3
    window_size: 10
    epsilon: 0.5
    patience: 5

# Logging
log:
  name: "frontal"
  log_dir: "./log_drl/"
  log_interval: 1
  throttle_duration: 0.5

# RL Algo
algo:
  name: "ppo"
  clip_range: 0.2
  batch_size: 128        
  n_epochs: 10            
  vf_coef: 0.5
  ent_coef: 0.005         
  learning_rate_schedule: "linear"
  seed: 42

# Policy network
policy:
  name: "drl-vo"
  features_dim: 256
  pi_layers: [256]
  vf_layers: [128]
  activation_fn: "tanh"

# Environment observations
env:
  name: "drl-vo"
  max_iteration: 5000
  max_time: 90
  normalize_reward: False #True
  normalize_observation: False

  obs:
    goal: true
    scan: true
    scan_dim: 720
    scan_history: 5
    scan_slice: 16 #4 
    scan_tile: 1
    human_number: 1
    humans: false

  reward:
    constant: -0.01
    goal_arrival: 20
    goal_waypoint: 5.0
    collision: -20
    scan: -0.2
    scan_penalty_threshold_factor: 1.5
    theta_angle: 0.0 #0.2
    rotation: -0.1
    human: 1.0
    human_personal_distance: 2.0

  robot:
    robot_radius: 0.35
    goal_radius: 0.2
    dist_goal_history_number: 10
    min_linear_velocity: 0.0
    max_linear_velocity: 0.5
    min_angular_velocity: -2.0
    max_angular_velocity: 2.0

  ros:
    robot_odom: "/robot_odom"
    robot_pose: "/robot_pose"
    cnn_data: "/cnn_data"
    global_goal: "/global_goal"
    cmd_vel: "/smooth_cmd_vel"
    reset_service: "/unity/reset"
