name: sarl_star

pre_window: 
  - source /opt/ros/humble/setup.bash
  - source ../../ros2_ws//install/setup.bash

windows:
  - navstack:
      layout: tiled
      panes:
        - shell:
        #Docker: ROS bridge + Sarl*
        - docker:
          - docker compose up
        #ROS2
        - bridge_unity:
          - ros2 run ros_tcp_endpoint default_server_endpoint
        - map_proxy:
          - ros2 run robotsnap map_proxy.py
        - rviz:
          - ros2 launch robotsnap rviz.launch.py
        - manager:
          - ros2 run robotsnap experiment_manager.py