version: "3.8"

networks:
  ros:
    driver: bridge

services:
  # BRNE
  brne:
    image: agouguet/benchmark-social-navigation:brne
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
    entrypoint: ''
    command: bash -c "sleep 1 && source /opt/ros/humble/setup.bash && source /root/brne_ws/install/setup.bash && stdbuf -o L ros2 launch crowd_nav algorithm.launch.xml"
    networks:
      - ros