name: simple

pre_window: 
  - source /opt/ros/humble/setup.bash
  - source ../../ros2_ws/install/setup.bash

windows:
  - navstack:
      layout: tiled
      panes:
        - shell:
        #ROS2
        - bridge_unity:
          - ros2 run ros_tcp_endpoint default_server_endpoint
        - nav:
          - ros2 launch robotsnap nav2.launch.py
        - map_publisher:
          - ros2 run robotsnap map_proxy.py
        - rviz:
          - ros2 launch robotsnap rviz.launch.py
        - clear_global_costmap:
          - ros2 service call /global_costmap/clear_entirely_global_costmap nav2_msgs/srv/ClearEntireCostmap -r 0.33
        - clear_local_costmap:
          - ros2 service call /local_costmap/clear_entirely_local_costmap nav2_msgs/srv/ClearEntireCostmap -r 0.33
        - manager:
          - ros2 run robotsnap experiment_manager.py