version: "3.8"

networks:
  ros:
    driver: bridge

services:
  # ROS MASTER
  ros-master:
    image: ros:noetic
    command: stdbuf -o L roscore
    networks:
      - ros

  # ROS BRIDGE
  ros_bridge:
    # image: ros:foxy-ros1-bridge
    image: my_ros1_bridge
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
    entrypoint: './ros_entrypoint.sh'
    command: stdbuf -o L ros2 run ros1_bridge dynamic_bridge --bridge-all-topics
    networks:
      - ros

  # HATEB
  hateb:
    image: agouguet/benchmark-social-navigation:hateb
    # image: ros:kinetic
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
    entrypoint: ''
    command: bash -c "sleep 1 && source /opt/ros/noetic/setup.bash && source /root/hateb_ws/devel/setup.bash && stdbuf -o L roslaunch --wait cohan_navigation social_sim_hateb.launch"
    networks:
      - ros